# Generated by Django 5.2.6 on 2025-09-26 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('LM', 'Lancha menor'), ('PM', 'Pesquera menor'), ('YT', 'Yate'), ('OT', 'Otro')], default='OT', max_length=2)),
                ('eslora_m', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('activa', models.BooleanField(default=True)),
                ('armador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naves', to='naves.armador')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='naves.nave')),
            ],
            options={
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
